const express = require("express")
const app = express()
app.set("view engine", "pug")
var path = require("path")
var staticpath = path.join(__dirname)
app.get("/", (req, res) => {
    res.render(staticpath + "/Simple")
    res.send()
})
app.listen(5050)